var pilot1 = new pilot;
pilot1.firstName = "Tzahi";
pilot1.lastName = "Hotuka";
pilot1.pilotLicenseNumber = 23564854;
pilot1.seniorityYears = 24;
pilot1.print();
var passenger1 = new passenger;
passenger1.passengerPassport = 649832468;
passenger1.print();
var flightAttendant1 = new flightAttendant;
flightAttendant1.firstName = "Tzahi";
flightAttendant1.lastName = "Hotuka";
flightAttendant1.originCountry = "USA";
flightAttendant1.seniorityYears = 12;
flightAttendant1.print();
var groundSteward1 = new groundSteward;
groundSteward1.firstName = "Tzahi";
groundSteward1.lastName = "Hotuka";
groundSteward1.groundPosition = "Reception Department";
groundSteward1.seniorityYears = 3;
groundSteward1.print();
//# sourceMappingURL=app.js.map